BaseApp/urls.py
from django.urls import path
from django.urls import include
from django.urls import re_path
from BaseApp import views

app_name = 'base_app'

urlpatterns = [
    path('', views.HomeView.as_view()),
    path('home/', views.HomeView.as_view(), name='Home'),
    path('poll_search/', views.PollSearch.as_view(), name='poll_search'),
    path('poll_list/', views.PollList.as_view(), name='poll_list'),
    path('poll_list/<str:question_topic>', views.PollList.as_view(), name='poll_list'),
    path('poll/<int:question_id>/', views.PollView.as_view(), name='poll'),
    path('add_poll/', views.AddPollView.as_view(), name='add_poll'),
    path('profile/', views.Profile.as_view(), name='Profile'),
    path('user_login/', views.user_login, name="user_login"),
    path('user_logout/', views.user_logout, name="user_logout"),
    path('user_register/', views.register, name="user_register")
]

OnlinePoll/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.urls import re_path
from BaseApp.views import HomeView
from BaseApp import urls as BaseApp_urls
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(BaseApp_urls)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BaseApp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="user_profile")
    user_points = models.PositiveIntegerField(default=1)
    profile_pic = models.ImageField(upload_to='profile_pic', blank=True, null=True, default='')

    def __str__(self):
        return self.user.username

class Question(models.Model):
    user = models.ForeignKey('UserProfile', on_delete=models.CASCADE)
    question_text = models.CharField(max_length=300, blank=False)
    question_topic = models.CharField(max_length=300, default="Misc")
    question_comments = models.TextField(max_length=500, blank=True)
    responders = models.ManyToManyField(UserProfile, related_name="questions")

    def __str__(self):
        return str(self.question_text)

class Option(models.Model):
    question = models.ForeignKey('Question', on_delete=models.CASCADE)
    option_text = models.CharField(max_length=200, blank=False)
    vote_count = models.PositiveIntegerField()

    def __str__(self):
        return str(self.option_text)

BaseApp/forms.py
form django import forms

BaseApp/views.py
from django.shortcuts import render
from django.views import View
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from BaseApp.models import UserProfile, Question, Option
from django.contrib.auth.models import User
from BaseApp import content_util as c_util
from django.core.exceptions import ObjectDoesNotExist

# Create your views here.
class HomeView(View):
    template_name = 'BaseApp/base.html'

    def get(self, request):
        return render(request, self.template_name, {'list_title':'Home', 'question_list':c_util.getTopQuestions(3)})

class AddPollView(View):
    template_name = "BaseApp/add_poll.html"
    ctxt = {'list_title':'Add Poll'}

    def get(self, request):
        if request.user.is_authenticated:
            return render(request, self.template_name, context=self.ctxt)

        return HttpResponseRedirect(reverse("base_app:Home"))


    def post(self, request):
        if request.user.is_authenticated:
            question_text = request.POST.get("question_text")
            question_topic = request.POST.get("question_topic")
            question_comments = request.POST.get("question_comments")

            option1 = request.POST.get("option1")
            option2 = request.POST.get("option2")
            option3 = request.POST.get("option3")
            option4 = request.POST.get("option4")

            currentUser, obj = UserProfile.objects.get_or_create(user=request.user)
            question = Question.objects.create(user=currentUser, question_text=question_text, question_topic=question_topic, question_comments=question_comments)
            question.save()

            if option1 != "":
                op1 = Option.objects.create(question=question, option_text=option1, vote_count=0)
                op1.save()

            if option2 != "":
                op2 = Option.objects.create(question=question, option_text=option2, vote_count=0)
                op2.save()

            if option3 != "":
                op3 = Option.objects.create(question=question, option_text=option3, vote_count=0)
                op3.save()

            if option4 != "":
                op4 = Option.objects.create(question=question, option_text=option4, vote_count=0)
                op4.save()

        return render(request, self.template_name, context=self.ctxt)

class PollView(View):
    template_name = "BaseApp/poll.html"

    def get(self, request, question_id):
        q = c_util.getQuestion(question_id)
        optionList = c_util.getOptions(q)
        ctxt = {'list_title':'Poll'}
        ctxt['question'] = q
        ctxt['optionList'] = optionList
        ctxt['disableDone'] = True

        if request.user.is_authenticated:
            currentUser, obj = UserProfile.objects.get_or_create(user=request.user)
            try:
                currentUser.questions.get(id=question_id)
            except ObjectDoesNotExist:
                ctxt['disableDone'] = False

        return render(request, self.template_name, context=ctxt)

    def post(self, request, question_id):
        q = c_util.getQuestion(question_id)
        optionList = c_util.getOptions(q)
        ctxt = {'list_title':'Poll'}
        ctxt['question'] = q
        ctxt['optionList'] = optionList
        ctxt['disableDone'] = True

        if request.user.is_authenticated:
            selected_option_id = request.POST.get("option")
            currentUser, obj = UserProfile.objects.get_or_create(user=request.user)
            option = Option.objects.get(id=selected_option_id)

            try:
                option.question.responders.get(id=currentUser.id)
            except ObjectDoesNotExist:
                option.question.responders.add(currentUser)
                option.vote_count += 1
                currentUser.user_points += 1
                option.save()
                currentUser.save()

        return render(request, self.template_name, context=ctxt)

class PollList(View):
    template_name = "BaseApp/poll_list.html"
    list_title = "List"
    ctxt = {'list_title':list_title}

    def get(self, request, question_topic=""):
        if question_topic is not "":
            self.ctxt['question_list'] = c_util.getQuestionsByTopic(question_topic)
            return render(request, self.template_name, context=self.ctxt)
        else:
            if request.user.is_authenticated:
                currentUser, obj = UserProfile.objects.get_or_create(user=request.user)
                self.ctxt['question_list'] = c_util.getQuestionsByUser(currentUser)
                return render(request, self.template_name, context=self.ctxt)
        return HttpResponseRedirect(reverse("base_app:Home"))

class PollSearch(View):
    template_name = "BaseApp/poll_search.html"
    list_title = "Search"

    def get(self, request):
        return render(request, self.template_name, context={'list_title':self.list_title})

    def post(self, request):
        searchQuery = request.POST.get("searchQuery")
        return render(request, self.template_name, context={'list_title':self.list_title, 'question_list':c_util.queryQuestions(searchQuery)})

class Profile(View):
    template_name = "BaseApp/profile.html"
    list_title =     list_title = "Profile"
    ctxt = {'list_title':list_title}

    def get(self, request):
        return render(request, self.template_name, context=self.ctxt)

def register(request):
    print("REGISTER CALLED")
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        email = request.POST.get("email")

        # TODO: Perform a check against same username
        if(False):
            return render(HttpResponse("User already exist. TODO: Display better"))

        if(password != request.POST.get("confirm-password")):
            return render(HttpResponse("Password doesnt match with confirm password (TODO: Display better)"))

        # TODO: Perform validations on form here

        user = User.objects.create_user(username=username, email=email, password=password)
        user.save()

        user_profile = UserProfile.objects.create(user=user)

        if 'profile_pic' in request.FILES:
            print("FILE NAME: ")
            print(request.FILES['profile_pic'].name)
            request.FILES['profile_pic'].name = str(user_profile.id)+"_"+request.FILES['profile_pic'].name

            user_profile.profile_pic = request.FILES['profile_pic']

        user_profile.save()

        user = authenticate(username=username, password=password) # TODO: try after removing this line

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('base_app:Home'))
            else:
                return HttpResponse("Account Not Active todo: have a better display")
        else:
            return HttpResponse("Something is not right with signup login")

        return HttpResponse("Try pushing signup button")

    return HttpResponse("Try pushing sign up button 2")


def user_login(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse("base_app:Home"))
            else:
                return HttpResponse("Account Not Active todo: have a better display")
        else:
            print("Login Failed: username: {}, password: {}".format(username, password))
            return HttpResponse("Invalid Login Details")
    else:
        render(request, reverse("base_app:Home"), {'list_title':'Home'})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse("base_app:Home"))

templates/BaseApp/add_poll.html
{% extends 'BaseApp/base.html' %}

{% block main_list_block %}
  {% if user.is_authenticated %}
    <div class="main_list container">

      <form class="form-group" action="{% url 'base_app:add_poll' %}" method="POST">
        {% csrf_token %}
        <input type="text" placeholder="Type your question here" name="question_text" class="form-control">
        <br><br>

        <!-- TODO: Add buttons for dynamic inputs -->
        <input type="text" placeholder="Type option 1" name="option1" class="form-control"><br>
        <input type="text" placeholder="Type option 2" name="option2" class="form-control"><br>
        <input type="text" placeholder="Type option 3" name="option3" class="form-control"><br>
        <input type="text" placeholder="Type option 4" name="option4" class="form-control"><br>
        <br>

        <input type="text" name="question_topic" default="Misc" placeholder="Question Topic" class="form-control"><br>
        <input type="text" name="question_comments" default="---" placeholder="Question Comment" class="form-control"><br>

        <button type="submit" name="button" class="btn btn-success">Lets Do It</button>
      </form>
    </div>

  {% endif %}
{% endblock %}

{% block topic_block %} {% endblock %}

templates/BaseApp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <title>{% block title_block %} Poll App - Home {% endblock %}</title>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light nav-fill">
      <a class="navbar-brand" href="{% url 'base_app:Home' %}">Open Poll</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'base_app:Home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'base_app:poll_search' %}">Search Polls</a>
          </li>
          <li>
            {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'base_app:add_poll' %}">Add Poll</a>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'base_app:user_logout' %}">Logout</a>
            </li>
            {% else %}
              <button type="button" class="nav-item btn btn-outline-success" data-toggle="modal" data-target="#loginModal" name="button">LogIn</button>
              <li class="nav-item">
                <a class="nav-link" data-toggle="modal" data-target="#signupModal" href="#">SignUp</a>
              </li>
            {% endif %}
          </li>
        </ul>
      </div>
    </nav>

  <!-- Login Modal -->
  <div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="loginModalLabel">Login</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>

        <div class="modal-body">
          <form method="POST" action="{% url 'base_app:user_login' %}"> <!-- TODO: check of django Form will work here -->
            {% csrf_token %}
            <div class="form-group">
              <input type="text" placeholder="username" class="form-control" name="username">
            </div>
            <div class="form-group">
              <input type="password" placeholder="password" class="form-control" name="password">
            </div>
            <div class="modal-footer">
              <button type="submit" class="btn btn-success">Login</button>
            </div>
          </form>
        </div>

        <div class="container">
          <p>Dont have an account? <button class="btn btn-link" data-dismiss="modal" data-toggle="modal" data-target="#signupModal">SignUp here!</button></p>
        </div>

      </div>
    </div>
  </div>

  <!-- SignUp Modal -->
  <div class="modal fade" id="signupModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="signupModalLabel">SignUp</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <form method="POST" enctype="multipart/form-data" action="{% url 'base_app:user_register' %}"> <!-- TODO: check of django Form will work here -->
            {% csrf_token %}
            <div class="form-group">
              <label for="profile_pic">Profile Pic</label>
              <input type="file" name="profile_pic" class="form-control-file">
            </div>
            <div class="form-group">
              <input type="text" placeholder="Username" class="form-control" name="username">
            </div>
            <div class="form-group">
              <input type="email" placeholder="Email" class="form-control" name="email">
            </div>
            <div class="form-group">
              <input type="password" placeholder="Password" class="form-control" name="password">
            </div>
            <div class="form-group">
              <input type="password" placeholder="Confirm Password" class="form-control" name="confirm-password">
            </div>
            <div class="modal-footer">
              <button type="submit" class="btn btn-success user_buttons">SignUp</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>

  <div class="jumbotron">
    <h1>{{ list_title }}</h1>
  </div>


    {% block left_block %}
    </div>
    <div class="profile_info container">
      <table>
        {%if user.user_profile.profile_pic %}
          <tr><td> <img src="{{ MEDIA_URL }}{{ user.user_profile.profile_pic }}" height="100" width="100" alt="Avatar" style="border-radius:50%"> <br><br> </td></tr>
        {% endif %}
        <tr><td>{{ user.username }}</td></tr>
        <tr><td>Points: {{ user.user_profile.user_points }}</td></tr>
        <tr><td>Followers: {Follower Count}</td></tr>
        <tr><td>Following: {Following Count}</td></tr>
        {% if user.is_authenticated %}
        <tr><td><a href="{% url 'base_app:poll_list' %}">My Polls</a></td></tr> <!-- TODO: Add poll page for this -->
        {% endif %}
      </table>
    </div>

    {% endblock %}

    {% block main_list_block %}

    {% block search_block %} {% endblock %}

      <div class="main_list container">
        <table>

          {% for q in question_list %}
            <tr>
              <table>
                <tr> <td> <a href="{% url 'base_app:poll' q.id %}"> <h3> {{q.question_text}} </h3> </a> </td></tr>
                <tr> <td> {{q.question_comments}} </td></tr>
              </table>
              <br>
              <br>
            </tr>
          {% endfor %}
        </table>
      </div>
    {% endblock %}

    {% block topic_block %}
      <div class=" container topic_list">
        <table>
          {% for q in question_list %}
            <tr> <td><h3> <a href="{% url 'base_app:poll_list' q.question_topic %}"> {{ q.question_topic }}</a></h3></td></tr>
          {% endfor %}
          <!-- <tr> <td><td><h3>TOPIC 1</h3></td> <td>Some details about topic 1</td> </td></tr>
          <tr> <td><td><h3>TOPIC 2</h3></td> <td>Some details about topic 2</td> </td></tr>
          <tr> <td><td><h3>TOPIC 3</h3></td> <td>Some details about topic 3</td> </td></tr>
          <tr> <td><td><h3>TOPIC 4</h3></td> <td>Some details about topic 4</td> </td></tr>
          <tr> <td><td><h3>TOPIC 5</h3></td> <td>Some details about topic 5</td> </td> </tr> -->
        </table>
      </div>
    {% endblock %}

  </body>
</html>

templates/BaseApp/poll.html
{% extends 'BaseApp/base.html' %}

{% block main_list_block %}

  <div class="main_list container">
    <h3> {{ question.question_text }} </h3>
    <br>
    <form method="POST">
      {% csrf_token %}
      {% for option in optionList %}
        <input type="radio" name="option" value="{{option.id}}">
        <label for="{{ option.option_text }}">{{ option.option_text }}</label>
        <br>
      {% endfor %}
      <br>
      {% if disableDone %}
      <button type="submit" class="btn btn-lg btn-block btn-outline-success user_buttons" value="Submit" disabled>Done</button>
      {% else %}
      <!-- TODO: Display the dialog to login here -->
      <button type="submit" class="btn btn-lg btn-block btn-outline-success user_buttons" value="Submit">Done</button>
      {% endif %}
    </form>
  </div>
  {% endblock %}

templates/BaseApp/poll_list.html
<!DOCTYPE html>
{% extends 'BaseApp/base.html' %}

  {% block title_block %} {{ list_title }} {% endblock %}

      {% block search_block %}
      {% endblock %}

      {% block topic_block %}{% endblock %}

templates/BaseApp/poll_search.html
<!DOCTYPE html>
{% extends 'BaseApp/base.html' %}

  {% block title_block %} {{ list_title }} {% endblock %}

      {% block search_block %}
        <div class="container">
          <form class="form-inline my-2 my-lg-0" method="POST">
            {% csrf_token %}
            <input class="form-control mr-sm-2" type="search" name="searchQuery" action="#" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
          <br><br>
        </div>
      {% endblock %}

      {% block topic_block %}{% endblock %}

templates/BaseApp/profile.html
{%extends 'BaseApp/base.html'%}

{% block left_block %} {% endblock %}

{% block main_list_block %} {% endblock %}